SELECT HISTORY_ID, 
    round(DAILY_FEE * (DATEDIFF(h.END_DATE,h.START_DATE)+1)
    * (case 
    when DATEDIFF(END_DATE,START_DATE)+1 < 7 then 1
    when DATEDIFF(END_DATE,START_DATE)+1 < 30 then 0.95
    when DATEDIFF(END_DATE,START_DATE)+1 < 90 then 0.92
    else 0.85 end)) as "FEE"
    -- 트럭이 조건이므로 트럭일 때 할인율만 알아내면 된다.
    -- 7일 이상일 때 5%, 

from CAR_RENTAL_COMPANY_CAR as c 
    join CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
    on c.CAR_ID = h.CAR_ID
    join CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p
    on c.CAR_TYPE = p.CAR_TYPE

where c.car_type = "트럭"

group by HISTORY_ID

order by FEE desc , HISTORY_ID desc


-- ////////////////////////////////////////////////////////////////////////////////////////


-- WITH ~ AS () : 새로운 가상 테이블을 만듦.
WITH RENT_INFO AS (
    SELECT HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DAYS, DAILY_FEE, CAR_TYPE,
       CASE
           WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
           WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
           WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
       ELSE '' END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT RENT_INFO.HISTORY_ID, 
       ROUND(RENT_INFO.DAILY_FEE * RENT_INFO.RENT_DAYS * (100 - IFNULL(PLAN.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM RENT_INFO RIGHT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
    ON PLAN.DURATION_TYPE = RENT_INFO.DURATION_TYPE AND PLAN.CAR_TYPE = RENT_INFO.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;
