-- CONCAT -> 여러 문자열를 하나의 문자열로 합치기
SELECT CONCAT("/home/grep/src/", a.BOARD_ID, "/", b.FILE_ID, b.FILE_NAME, b.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_FILE b
ON a.BOARD_ID = b.BOARD_ID
WHERE VIEWS = (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY FILE_ID DESC
