
SELECT a.CAR_ID,a.CAR_TYPE,
ROUND(a.DAILY_FEE*30*(100-c.DISCOUNT_RATE)/100) AS FEE

from CAR_RENTAL_COMPANY_CAR a 
join CAR_RENTAL_COMPANY_RENTAL_HISTORY b
on  a.CAR_ID = b.CAR_ID
join CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
on a.CAR_TYPE = c.CAR_TYPE

WHERE a.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND c.DURATION_TYPE='30일 이상'
and  a.CAR_TYPE IN ('세단', 'SUV')

group by a.CAR_ID
having FEE>=500000 AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
